// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.outscale.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.outscale.inputs.GetNatServiceFilterArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetNatServiceArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNatServiceArgs Empty = new GetNatServiceArgs();

    /**
     * A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
     * 
     */
    @Import(name="filters")
    private @Nullable Output<List<GetNatServiceFilterArgs>> filters;

    /**
     * @return A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
     * 
     */
    public Optional<Output<List<GetNatServiceFilterArgs>>> filters() {
        return Optional.ofNullable(this.filters);
    }

    /**
     * The ID of the NAT service.
     * 
     */
    @Import(name="natServiceId")
    private @Nullable Output<String> natServiceId;

    /**
     * @return The ID of the NAT service.
     * 
     */
    public Optional<Output<String>> natServiceId() {
        return Optional.ofNullable(this.natServiceId);
    }

    private GetNatServiceArgs() {}

    private GetNatServiceArgs(GetNatServiceArgs $) {
        this.filters = $.filters;
        this.natServiceId = $.natServiceId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNatServiceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNatServiceArgs $;

        public Builder() {
            $ = new GetNatServiceArgs();
        }

        public Builder(GetNatServiceArgs defaults) {
            $ = new GetNatServiceArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param filters A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
         * 
         * @return builder
         * 
         */
        public Builder filters(@Nullable Output<List<GetNatServiceFilterArgs>> filters) {
            $.filters = filters;
            return this;
        }

        /**
         * @param filters A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
         * 
         * @return builder
         * 
         */
        public Builder filters(List<GetNatServiceFilterArgs> filters) {
            return filters(Output.of(filters));
        }

        /**
         * @param filters A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
         * 
         * @return builder
         * 
         */
        public Builder filters(GetNatServiceFilterArgs... filters) {
            return filters(List.of(filters));
        }

        /**
         * @param natServiceId The ID of the NAT service.
         * 
         * @return builder
         * 
         */
        public Builder natServiceId(@Nullable Output<String> natServiceId) {
            $.natServiceId = natServiceId;
            return this;
        }

        /**
         * @param natServiceId The ID of the NAT service.
         * 
         * @return builder
         * 
         */
        public Builder natServiceId(String natServiceId) {
            return natServiceId(Output.of(natServiceId));
        }

        public GetNatServiceArgs build() {
            return $;
        }
    }

}
