// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.outscale.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.outscale.inputs.GetProductTypesFilterArgs;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetProductTypesArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetProductTypesArgs Empty = new GetProductTypesArgs();

    /**
     * A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
     * 
     */
    @Import(name="filters")
    private @Nullable Output<List<GetProductTypesFilterArgs>> filters;

    /**
     * @return A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
     * 
     */
    public Optional<Output<List<GetProductTypesFilterArgs>>> filters() {
        return Optional.ofNullable(this.filters);
    }

    private GetProductTypesArgs() {}

    private GetProductTypesArgs(GetProductTypesArgs $) {
        this.filters = $.filters;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetProductTypesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetProductTypesArgs $;

        public Builder() {
            $ = new GetProductTypesArgs();
        }

        public Builder(GetProductTypesArgs defaults) {
            $ = new GetProductTypesArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param filters A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
         * 
         * @return builder
         * 
         */
        public Builder filters(@Nullable Output<List<GetProductTypesFilterArgs>> filters) {
            $.filters = filters;
            return this;
        }

        /**
         * @param filters A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
         * 
         * @return builder
         * 
         */
        public Builder filters(List<GetProductTypesFilterArgs> filters) {
            return filters(Output.of(filters));
        }

        /**
         * @param filters A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
         * 
         * @return builder
         * 
         */
        public Builder filters(GetProductTypesFilterArgs... filters) {
            return filters(List.of(filters));
        }

        public GetProductTypesArgs build() {
            return $;
        }
    }

}
