// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.outscale.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.outscale.inputs.GetSnapshotsFilter;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetSnapshotsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSnapshotsPlainArgs Empty = new GetSnapshotsPlainArgs();

    /**
     * The account ID of the owner of the snapshot.
     * 
     */
    @Import(name="accountIds")
    private @Nullable List<String> accountIds;

    /**
     * @return The account ID of the owner of the snapshot.
     * 
     */
    public Optional<List<String>> accountIds() {
        return Optional.ofNullable(this.accountIds);
    }

    /**
     * A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
     * 
     */
    @Import(name="filters")
    private @Nullable List<GetSnapshotsFilter> filters;

    /**
     * @return A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
     * 
     */
    public Optional<List<GetSnapshotsFilter>> filters() {
        return Optional.ofNullable(this.filters);
    }

    @Import(name="permissionToCreateVolumes")
    private @Nullable List<String> permissionToCreateVolumes;

    public Optional<List<String>> permissionToCreateVolumes() {
        return Optional.ofNullable(this.permissionToCreateVolumes);
    }

    /**
     * The ID of the snapshot.
     * 
     */
    @Import(name="snapshotIds")
    private @Nullable List<String> snapshotIds;

    /**
     * @return The ID of the snapshot.
     * 
     */
    public Optional<List<String>> snapshotIds() {
        return Optional.ofNullable(this.snapshotIds);
    }

    private GetSnapshotsPlainArgs() {}

    private GetSnapshotsPlainArgs(GetSnapshotsPlainArgs $) {
        this.accountIds = $.accountIds;
        this.filters = $.filters;
        this.permissionToCreateVolumes = $.permissionToCreateVolumes;
        this.snapshotIds = $.snapshotIds;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSnapshotsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSnapshotsPlainArgs $;

        public Builder() {
            $ = new GetSnapshotsPlainArgs();
        }

        public Builder(GetSnapshotsPlainArgs defaults) {
            $ = new GetSnapshotsPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountIds The account ID of the owner of the snapshot.
         * 
         * @return builder
         * 
         */
        public Builder accountIds(@Nullable List<String> accountIds) {
            $.accountIds = accountIds;
            return this;
        }

        /**
         * @param accountIds The account ID of the owner of the snapshot.
         * 
         * @return builder
         * 
         */
        public Builder accountIds(String... accountIds) {
            return accountIds(List.of(accountIds));
        }

        /**
         * @param filters A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
         * 
         * @return builder
         * 
         */
        public Builder filters(@Nullable List<GetSnapshotsFilter> filters) {
            $.filters = filters;
            return this;
        }

        /**
         * @param filters A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
         * 
         * @return builder
         * 
         */
        public Builder filters(GetSnapshotsFilter... filters) {
            return filters(List.of(filters));
        }

        public Builder permissionToCreateVolumes(@Nullable List<String> permissionToCreateVolumes) {
            $.permissionToCreateVolumes = permissionToCreateVolumes;
            return this;
        }

        public Builder permissionToCreateVolumes(String... permissionToCreateVolumes) {
            return permissionToCreateVolumes(List.of(permissionToCreateVolumes));
        }

        /**
         * @param snapshotIds The ID of the snapshot.
         * 
         * @return builder
         * 
         */
        public Builder snapshotIds(@Nullable List<String> snapshotIds) {
            $.snapshotIds = snapshotIds;
            return this;
        }

        /**
         * @param snapshotIds The ID of the snapshot.
         * 
         * @return builder
         * 
         */
        public Builder snapshotIds(String... snapshotIds) {
            return snapshotIds(List.of(snapshotIds));
        }

        public GetSnapshotsPlainArgs build() {
            return $;
        }
    }

}
