// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.outscale.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.outscale.inputs.GetVirtualGatewaysFilterArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetVirtualGatewaysArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetVirtualGatewaysArgs Empty = new GetVirtualGatewaysArgs();

    /**
     * A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
     * 
     */
    @Import(name="filters")
    private @Nullable Output<List<GetVirtualGatewaysFilterArgs>> filters;

    /**
     * @return A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
     * 
     */
    public Optional<Output<List<GetVirtualGatewaysFilterArgs>>> filters() {
        return Optional.ofNullable(this.filters);
    }

    /**
     * The ID of the virtual gateway.
     * 
     */
    @Import(name="virtualGatewayIds")
    private @Nullable Output<List<String>> virtualGatewayIds;

    /**
     * @return The ID of the virtual gateway.
     * 
     */
    public Optional<Output<List<String>>> virtualGatewayIds() {
        return Optional.ofNullable(this.virtualGatewayIds);
    }

    private GetVirtualGatewaysArgs() {}

    private GetVirtualGatewaysArgs(GetVirtualGatewaysArgs $) {
        this.filters = $.filters;
        this.virtualGatewayIds = $.virtualGatewayIds;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetVirtualGatewaysArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetVirtualGatewaysArgs $;

        public Builder() {
            $ = new GetVirtualGatewaysArgs();
        }

        public Builder(GetVirtualGatewaysArgs defaults) {
            $ = new GetVirtualGatewaysArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param filters A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
         * 
         * @return builder
         * 
         */
        public Builder filters(@Nullable Output<List<GetVirtualGatewaysFilterArgs>> filters) {
            $.filters = filters;
            return this;
        }

        /**
         * @param filters A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
         * 
         * @return builder
         * 
         */
        public Builder filters(List<GetVirtualGatewaysFilterArgs> filters) {
            return filters(Output.of(filters));
        }

        /**
         * @param filters A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
         * 
         * @return builder
         * 
         */
        public Builder filters(GetVirtualGatewaysFilterArgs... filters) {
            return filters(List.of(filters));
        }

        /**
         * @param virtualGatewayIds The ID of the virtual gateway.
         * 
         * @return builder
         * 
         */
        public Builder virtualGatewayIds(@Nullable Output<List<String>> virtualGatewayIds) {
            $.virtualGatewayIds = virtualGatewayIds;
            return this;
        }

        /**
         * @param virtualGatewayIds The ID of the virtual gateway.
         * 
         * @return builder
         * 
         */
        public Builder virtualGatewayIds(List<String> virtualGatewayIds) {
            return virtualGatewayIds(Output.of(virtualGatewayIds));
        }

        /**
         * @param virtualGatewayIds The ID of the virtual gateway.
         * 
         * @return builder
         * 
         */
        public Builder virtualGatewayIds(String... virtualGatewayIds) {
            return virtualGatewayIds(List.of(virtualGatewayIds));
        }

        public GetVirtualGatewaysArgs build() {
            return $;
        }
    }

}
