// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.outscale;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.outscale.ServerCertificateArgs;
import com.pulumi.outscale.Utilities;
import com.pulumi.outscale.inputs.ServerCertificateState;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages a server certificate.
 * 
 * For more information on this resource, see the [User Guide](https://docs.outscale.com/en/userguide/About-Server-Certificates-in-EIM.html).\
 * For more information on this resource actions, see the [API documentation](https://docs.outscale.com/api#3ds-outscale-api-servercertificate).
 * 
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.outscale.ServerCertificate;
 * import com.pulumi.outscale.ServerCertificateArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var serverCertificate01 = new ServerCertificate(&#34;serverCertificate01&#34;, ServerCertificateArgs.builder()        
 *             .body(Files.readString(Paths.get(&#34;&lt;PATH&gt;&#34;)))
 *             .chain(Files.readString(Paths.get(&#34;&lt;PATH&gt;&#34;)))
 *             .privateKey(Files.readString(Paths.get(&#34;&lt;PATH&gt;&#34;)))
 *             .path(&#34;&lt;PATH&gt;&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * A server certificate can be imported using its ID. For exampleconsole
 * 
 * ```sh
 *  $ pulumi import outscale:index/serverCertificate:ServerCertificate ImportedServerCertificate 0123456789
 * ```
 * 
 */
@ResourceType(type="outscale:index/serverCertificate:ServerCertificate")
public class ServerCertificate extends com.pulumi.resources.CustomResource {
    /**
     * The PEM-encoded X509 certificate.
     * 
     */
    @Export(name="body", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> body;

    /**
     * @return The PEM-encoded X509 certificate.
     * 
     */
    public Output<Optional<String>> body() {
        return Codegen.optional(this.body);
    }
    /**
     * The PEM-encoded intermediate certification authorities.
     * 
     */
    @Export(name="chain", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> chain;

    /**
     * @return The PEM-encoded intermediate certification authorities.
     * 
     */
    public Output<Optional<String>> chain() {
        return Codegen.optional(this.chain);
    }
    @Export(name="dryRun", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> dryRun;

    public Output<Optional<String>> dryRun() {
        return Codegen.optional(this.dryRun);
    }
    /**
     * The date at which the server certificate expires.
     * 
     */
    @Export(name="expirationDate", refs={String.class}, tree="[0]")
    private Output<String> expirationDate;

    /**
     * @return The date at which the server certificate expires.
     * 
     */
    public Output<String> expirationDate() {
        return this.expirationDate;
    }
    /**
     * A unique name for the certificate. Constraints: 1-128 alphanumeric characters, pluses (+), equals (=), commas (,), periods (.), at signs (@), minuses (-), or underscores (_).
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return A unique name for the certificate. Constraints: 1-128 alphanumeric characters, pluses (+), equals (=), commas (,), periods (.), at signs (@), minuses (-), or underscores (_).
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The Outscale Resource Name (ORN) of the server certificate. For more information, see [Resource Identifiers &gt; Outscale Resource Names (ORNs)](https://docs.outscale.com/en/userguide/Resource-Identifiers.html#_outscale_resource_names_orns).
     * 
     */
    @Export(name="orn", refs={String.class}, tree="[0]")
    private Output<String> orn;

    /**
     * @return The Outscale Resource Name (ORN) of the server certificate. For more information, see [Resource Identifiers &gt; Outscale Resource Names (ORNs)](https://docs.outscale.com/en/userguide/Resource-Identifiers.html#_outscale_resource_names_orns).
     * 
     */
    public Output<String> orn() {
        return this.orn;
    }
    /**
     * The path to the server certificate, set to a slash (/) if not specified.
     * 
     */
    @Export(name="path", refs={String.class}, tree="[0]")
    private Output<String> path;

    /**
     * @return The path to the server certificate, set to a slash (/) if not specified.
     * 
     */
    public Output<String> path() {
        return this.path;
    }
    /**
     * The PEM-encoded private key matching the certificate.
     * 
     */
    @Export(name="privateKey", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> privateKey;

    /**
     * @return The PEM-encoded private key matching the certificate.
     * 
     */
    public Output<Optional<String>> privateKey() {
        return Codegen.optional(this.privateKey);
    }
    @Export(name="requestId", refs={String.class}, tree="[0]")
    private Output<String> requestId;

    public Output<String> requestId() {
        return this.requestId;
    }
    /**
     * The date at which the server certificate has been uploaded.
     * 
     */
    @Export(name="uploadDate", refs={String.class}, tree="[0]")
    private Output<String> uploadDate;

    /**
     * @return The date at which the server certificate has been uploaded.
     * 
     */
    public Output<String> uploadDate() {
        return this.uploadDate;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ServerCertificate(String name) {
        this(name, ServerCertificateArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ServerCertificate(String name, @Nullable ServerCertificateArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ServerCertificate(String name, @Nullable ServerCertificateArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("outscale:index/serverCertificate:ServerCertificate", name, args == null ? ServerCertificateArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private ServerCertificate(String name, Output<String> id, @Nullable ServerCertificateState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("outscale:index/serverCertificate:ServerCertificate", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ServerCertificate get(String name, Output<String> id, @Nullable ServerCertificateState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ServerCertificate(name, id, state, options);
    }
}
