// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Outscale.Outputs
{

    [OutputType]
    public sealed class GetAccountsAccountResult
    {
        /// <summary>
        /// The ID of the account.
        /// </summary>
        public readonly string AccountId;
        /// <summary>
        /// One or more additional email addresses for the account. These addresses are used for notifications only.
        /// </summary>
        public readonly ImmutableArray<string> AdditionalEmails;
        /// <summary>
        /// The city of the account owner.
        /// </summary>
        public readonly string City;
        /// <summary>
        /// The name of the company for the account.
        /// </summary>
        public readonly string CompanyName;
        /// <summary>
        /// The country of the account owner.
        /// </summary>
        public readonly string Country;
        /// <summary>
        /// The ID of the customer.
        /// </summary>
        public readonly string CustomerId;
        /// <summary>
        /// The main email address for the account. This address is used for your credentials and for notifications.
        /// </summary>
        public readonly string Email;
        /// <summary>
        /// The first name of the account owner.
        /// </summary>
        public readonly string FirstName;
        /// <summary>
        /// The job title of the account owner.
        /// </summary>
        public readonly string JobTitle;
        /// <summary>
        /// The last name of the account owner.
        /// </summary>
        public readonly string LastName;
        /// <summary>
        /// The mobile phone number of the account owner.
        /// </summary>
        public readonly string MobileNumber;
        /// <summary>
        /// The landline phone number of the account owner.
        /// </summary>
        public readonly string PhoneNumber;
        /// <summary>
        /// The state/province of the account.
        /// </summary>
        public readonly string StateProvince;
        /// <summary>
        /// The value added tax (VAT) number for the account.
        /// </summary>
        public readonly string VatNumber;
        /// <summary>
        /// The ZIP code of the city.
        /// </summary>
        public readonly string ZipCode;

        [OutputConstructor]
        private GetAccountsAccountResult(
            string accountId,

            ImmutableArray<string> additionalEmails,

            string city,

            string companyName,

            string country,

            string customerId,

            string email,

            string firstName,

            string jobTitle,

            string lastName,

            string mobileNumber,

            string phoneNumber,

            string stateProvince,

            string vatNumber,

            string zipCode)
        {
            AccountId = accountId;
            AdditionalEmails = additionalEmails;
            City = city;
            CompanyName = companyName;
            Country = country;
            CustomerId = customerId;
            Email = email;
            FirstName = firstName;
            JobTitle = jobTitle;
            LastName = lastName;
            MobileNumber = mobileNumber;
            PhoneNumber = phoneNumber;
            StateProvince = stateProvince;
            VatNumber = vatNumber;
            ZipCode = zipCode;
        }
    }
}
