// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Outscale.Outputs
{

    [OutputType]
    public sealed class GetPublicIpsPublicIpResult
    {
        /// <summary>
        /// (Required in a Net) The ID representing the association of the public IP with the VM or the NIC.
        /// </summary>
        public readonly string LinkPublicIpId;
        /// <summary>
        /// The account ID of the owner of the NIC.
        /// </summary>
        public readonly string NicAccountId;
        /// <summary>
        /// The ID of the NIC the public IP is associated with (if any).
        /// </summary>
        public readonly string NicId;
        /// <summary>
        /// The private IP associated with the public IP.
        /// </summary>
        public readonly string PrivateIp;
        /// <summary>
        /// The public IP.
        /// </summary>
        public readonly string PublicIp;
        /// <summary>
        /// The allocation ID of the public IP.
        /// </summary>
        public readonly string PublicIpId;
        /// <summary>
        /// One or more tags associated with the public IP.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetPublicIpsPublicIpTagResult> Tags;
        /// <summary>
        /// The ID of the VM the public IP is associated with (if any).
        /// </summary>
        public readonly string VmId;

        [OutputConstructor]
        private GetPublicIpsPublicIpResult(
            string linkPublicIpId,

            string nicAccountId,

            string nicId,

            string privateIp,

            string publicIp,

            string publicIpId,

            ImmutableArray<Outputs.GetPublicIpsPublicIpTagResult> tags,

            string vmId)
        {
            LinkPublicIpId = linkPublicIpId;
            NicAccountId = nicAccountId;
            NicId = nicId;
            PrivateIp = privateIp;
            PublicIp = publicIp;
            PublicIpId = publicIpId;
            Tags = tags;
            VmId = vmId;
        }
    }
}
