// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Outscale.Outputs
{

    [OutputType]
    public sealed class GetVmsVmActionsOnNextBootResult
    {
        /// <summary>
        /// One action to perform on the next boot of the VM. For more information, see [About Secure Boot](https://docs.outscale.com/en/userguide/About-Secure-Boot.html#_secure_boot_actions).
        /// </summary>
        public readonly string SecureBoot;

        [OutputConstructor]
        private GetVmsVmActionsOnNextBootResult(string secureBoot)
        {
            SecureBoot = secureBoot;
        }
    }
}
