---
- name: Install wordpress with docker
  hosts: all
  become: yes
  vars:
    default_container_name: snake
    default_container_image: aschil/snake:latest
  tasks:
  - name: Install package dependancy
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common   
        - python3-pip
      state: latest
      update_cache: true
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Install Docker repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present
  - name: Install Docker-Ce
    apt:
      name: docker-ce
      state: latest
      update_cache: yes
  
  - name: Install Docker Module for Python
    pip:
      name: docker
  - name: Pull docker image 
    community.docker.docker_image:
      name: "{{ default_container_image }}"
      source: pull
  
  - name: Docker run snake
    community.docker.docker_container:
      name: "{{ default_container_name }}"
      image: "{{ default_container_image }}"
      restart: true
      ports: 
      - "8080:8080"   