// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.outscale.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.outscale.outputs.GetApiAccessRulesApiAccessRule;
import com.pulumi.outscale.outputs.GetApiAccessRulesFilter;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class GetApiAccessRulesResult {
    /**
     * @return A list of API access rules.
     * 
     */
    private List<GetApiAccessRulesApiAccessRule> apiAccessRules;
    private @Nullable List<GetApiAccessRulesFilter> filters;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private String requestId;

    private GetApiAccessRulesResult() {}
    /**
     * @return A list of API access rules.
     * 
     */
    public List<GetApiAccessRulesApiAccessRule> apiAccessRules() {
        return this.apiAccessRules;
    }
    public List<GetApiAccessRulesFilter> filters() {
        return this.filters == null ? List.of() : this.filters;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String requestId() {
        return this.requestId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetApiAccessRulesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetApiAccessRulesApiAccessRule> apiAccessRules;
        private @Nullable List<GetApiAccessRulesFilter> filters;
        private String id;
        private String requestId;
        public Builder() {}
        public Builder(GetApiAccessRulesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.apiAccessRules = defaults.apiAccessRules;
    	      this.filters = defaults.filters;
    	      this.id = defaults.id;
    	      this.requestId = defaults.requestId;
        }

        @CustomType.Setter
        public Builder apiAccessRules(List<GetApiAccessRulesApiAccessRule> apiAccessRules) {
            this.apiAccessRules = Objects.requireNonNull(apiAccessRules);
            return this;
        }
        public Builder apiAccessRules(GetApiAccessRulesApiAccessRule... apiAccessRules) {
            return apiAccessRules(List.of(apiAccessRules));
        }
        @CustomType.Setter
        public Builder filters(@Nullable List<GetApiAccessRulesFilter> filters) {
            this.filters = filters;
            return this;
        }
        public Builder filters(GetApiAccessRulesFilter... filters) {
            return filters(List.of(filters));
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder requestId(String requestId) {
            this.requestId = Objects.requireNonNull(requestId);
            return this;
        }
        public GetApiAccessRulesResult build() {
            final var o = new GetApiAccessRulesResult();
            o.apiAccessRules = apiAccessRules;
            o.filters = filters;
            o.id = id;
            o.requestId = requestId;
            return o;
        }
    }
}
