// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.outscale.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.outscale.outputs.GetImageExportTasksFilter;
import com.pulumi.outscale.outputs.GetImageExportTasksImageExportTask;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class GetImageExportTasksResult {
    private Boolean dryRun;
    private @Nullable List<GetImageExportTasksFilter> filters;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return Information about one or more image export tasks.
     * 
     */
    private List<GetImageExportTasksImageExportTask> imageExportTasks;
    private String requestId;

    private GetImageExportTasksResult() {}
    public Boolean dryRun() {
        return this.dryRun;
    }
    public List<GetImageExportTasksFilter> filters() {
        return this.filters == null ? List.of() : this.filters;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Information about one or more image export tasks.
     * 
     */
    public List<GetImageExportTasksImageExportTask> imageExportTasks() {
        return this.imageExportTasks;
    }
    public String requestId() {
        return this.requestId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetImageExportTasksResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean dryRun;
        private @Nullable List<GetImageExportTasksFilter> filters;
        private String id;
        private List<GetImageExportTasksImageExportTask> imageExportTasks;
        private String requestId;
        public Builder() {}
        public Builder(GetImageExportTasksResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dryRun = defaults.dryRun;
    	      this.filters = defaults.filters;
    	      this.id = defaults.id;
    	      this.imageExportTasks = defaults.imageExportTasks;
    	      this.requestId = defaults.requestId;
        }

        @CustomType.Setter
        public Builder dryRun(Boolean dryRun) {
            this.dryRun = Objects.requireNonNull(dryRun);
            return this;
        }
        @CustomType.Setter
        public Builder filters(@Nullable List<GetImageExportTasksFilter> filters) {
            this.filters = filters;
            return this;
        }
        public Builder filters(GetImageExportTasksFilter... filters) {
            return filters(List.of(filters));
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder imageExportTasks(List<GetImageExportTasksImageExportTask> imageExportTasks) {
            this.imageExportTasks = Objects.requireNonNull(imageExportTasks);
            return this;
        }
        public Builder imageExportTasks(GetImageExportTasksImageExportTask... imageExportTasks) {
            return imageExportTasks(List.of(imageExportTasks));
        }
        @CustomType.Setter
        public Builder requestId(String requestId) {
            this.requestId = Objects.requireNonNull(requestId);
            return this;
        }
        public GetImageExportTasksResult build() {
            final var o = new GetImageExportTasksResult();
            o.dryRun = dryRun;
            o.filters = filters;
            o.id = id;
            o.imageExportTasks = imageExportTasks;
            o.requestId = requestId;
            return o;
        }
    }
}
