// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.outscale.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetLoadBalancersLoadBalancerLoadBalancerStickyCookiePolicy {
    /**
     * @return The name of the stickiness policy.
     * 
     */
    private String policyName;

    private GetLoadBalancersLoadBalancerLoadBalancerStickyCookiePolicy() {}
    /**
     * @return The name of the stickiness policy.
     * 
     */
    public String policyName() {
        return this.policyName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetLoadBalancersLoadBalancerLoadBalancerStickyCookiePolicy defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String policyName;
        public Builder() {}
        public Builder(GetLoadBalancersLoadBalancerLoadBalancerStickyCookiePolicy defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.policyName = defaults.policyName;
        }

        @CustomType.Setter
        public Builder policyName(String policyName) {
            this.policyName = Objects.requireNonNull(policyName);
            return this;
        }
        public GetLoadBalancersLoadBalancerLoadBalancerStickyCookiePolicy build() {
            final var o = new GetLoadBalancersLoadBalancerLoadBalancerStickyCookiePolicy();
            o.policyName = policyName;
            return o;
        }
    }
}
