// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.outscale.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.outscale.outputs.GetNicsNicLinkNic;
import com.pulumi.outscale.outputs.GetNicsNicLinkPublicIp;
import com.pulumi.outscale.outputs.GetNicsNicPrivateIp;
import com.pulumi.outscale.outputs.GetNicsNicSecurityGroup;
import com.pulumi.outscale.outputs.GetNicsNicTag;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetNicsNic {
    /**
     * @return The account ID of the owner of the NIC.
     * 
     */
    private String accountId;
    /**
     * @return The description of the NIC.
     * 
     */
    private String description;
    /**
     * @return (Net only) If true, the source/destination check is enabled. If false, it is disabled. This value must be false for a NAT VM to perform network address translation (NAT) in a Net.
     * 
     */
    private Boolean isSourceDestChecked;
    /**
     * @return Information about the NIC attachment.
     * 
     */
    private List<GetNicsNicLinkNic> linkNics;
    /**
     * @return Information about the public IP association.
     * 
     */
    private List<GetNicsNicLinkPublicIp> linkPublicIps;
    /**
     * @return The Media Access Control (MAC) address of the NIC.
     * 
     */
    private String macAddress;
    /**
     * @return The ID of the Net for the NIC.
     * 
     */
    private String netId;
    /**
     * @return The ID of the NIC.
     * 
     */
    private String nicId;
    /**
     * @return The name of the private DNS.
     * 
     */
    private String privateDnsName;
    /**
     * @return The private IPs of the NIC.
     * 
     */
    private List<GetNicsNicPrivateIp> privateIps;
    /**
     * @return One or more IDs of security groups for the NIC.
     * 
     */
    private List<GetNicsNicSecurityGroup> securityGroups;
    /**
     * @return The state of the NIC (`available` \| `attaching` \| `in-use` \| `detaching`).
     * 
     */
    private String state;
    /**
     * @return The ID of the Subnet.
     * 
     */
    private String subnetId;
    /**
     * @return The Subregion in which the NIC is located.
     * 
     */
    private String subregionName;
    /**
     * @return The key/value combinations of the tags associated with the NICs, in the following format: `TAGKEY=TAGVALUE`.
     * 
     */
    private List<GetNicsNicTag> tags;

    private GetNicsNic() {}
    /**
     * @return The account ID of the owner of the NIC.
     * 
     */
    public String accountId() {
        return this.accountId;
    }
    /**
     * @return The description of the NIC.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return (Net only) If true, the source/destination check is enabled. If false, it is disabled. This value must be false for a NAT VM to perform network address translation (NAT) in a Net.
     * 
     */
    public Boolean isSourceDestChecked() {
        return this.isSourceDestChecked;
    }
    /**
     * @return Information about the NIC attachment.
     * 
     */
    public List<GetNicsNicLinkNic> linkNics() {
        return this.linkNics;
    }
    /**
     * @return Information about the public IP association.
     * 
     */
    public List<GetNicsNicLinkPublicIp> linkPublicIps() {
        return this.linkPublicIps;
    }
    /**
     * @return The Media Access Control (MAC) address of the NIC.
     * 
     */
    public String macAddress() {
        return this.macAddress;
    }
    /**
     * @return The ID of the Net for the NIC.
     * 
     */
    public String netId() {
        return this.netId;
    }
    /**
     * @return The ID of the NIC.
     * 
     */
    public String nicId() {
        return this.nicId;
    }
    /**
     * @return The name of the private DNS.
     * 
     */
    public String privateDnsName() {
        return this.privateDnsName;
    }
    /**
     * @return The private IPs of the NIC.
     * 
     */
    public List<GetNicsNicPrivateIp> privateIps() {
        return this.privateIps;
    }
    /**
     * @return One or more IDs of security groups for the NIC.
     * 
     */
    public List<GetNicsNicSecurityGroup> securityGroups() {
        return this.securityGroups;
    }
    /**
     * @return The state of the NIC (`available` \| `attaching` \| `in-use` \| `detaching`).
     * 
     */
    public String state() {
        return this.state;
    }
    /**
     * @return The ID of the Subnet.
     * 
     */
    public String subnetId() {
        return this.subnetId;
    }
    /**
     * @return The Subregion in which the NIC is located.
     * 
     */
    public String subregionName() {
        return this.subregionName;
    }
    /**
     * @return The key/value combinations of the tags associated with the NICs, in the following format: `TAGKEY=TAGVALUE`.
     * 
     */
    public List<GetNicsNicTag> tags() {
        return this.tags;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNicsNic defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accountId;
        private String description;
        private Boolean isSourceDestChecked;
        private List<GetNicsNicLinkNic> linkNics;
        private List<GetNicsNicLinkPublicIp> linkPublicIps;
        private String macAddress;
        private String netId;
        private String nicId;
        private String privateDnsName;
        private List<GetNicsNicPrivateIp> privateIps;
        private List<GetNicsNicSecurityGroup> securityGroups;
        private String state;
        private String subnetId;
        private String subregionName;
        private List<GetNicsNicTag> tags;
        public Builder() {}
        public Builder(GetNicsNic defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountId = defaults.accountId;
    	      this.description = defaults.description;
    	      this.isSourceDestChecked = defaults.isSourceDestChecked;
    	      this.linkNics = defaults.linkNics;
    	      this.linkPublicIps = defaults.linkPublicIps;
    	      this.macAddress = defaults.macAddress;
    	      this.netId = defaults.netId;
    	      this.nicId = defaults.nicId;
    	      this.privateDnsName = defaults.privateDnsName;
    	      this.privateIps = defaults.privateIps;
    	      this.securityGroups = defaults.securityGroups;
    	      this.state = defaults.state;
    	      this.subnetId = defaults.subnetId;
    	      this.subregionName = defaults.subregionName;
    	      this.tags = defaults.tags;
        }

        @CustomType.Setter
        public Builder accountId(String accountId) {
            this.accountId = Objects.requireNonNull(accountId);
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }
        @CustomType.Setter
        public Builder isSourceDestChecked(Boolean isSourceDestChecked) {
            this.isSourceDestChecked = Objects.requireNonNull(isSourceDestChecked);
            return this;
        }
        @CustomType.Setter
        public Builder linkNics(List<GetNicsNicLinkNic> linkNics) {
            this.linkNics = Objects.requireNonNull(linkNics);
            return this;
        }
        public Builder linkNics(GetNicsNicLinkNic... linkNics) {
            return linkNics(List.of(linkNics));
        }
        @CustomType.Setter
        public Builder linkPublicIps(List<GetNicsNicLinkPublicIp> linkPublicIps) {
            this.linkPublicIps = Objects.requireNonNull(linkPublicIps);
            return this;
        }
        public Builder linkPublicIps(GetNicsNicLinkPublicIp... linkPublicIps) {
            return linkPublicIps(List.of(linkPublicIps));
        }
        @CustomType.Setter
        public Builder macAddress(String macAddress) {
            this.macAddress = Objects.requireNonNull(macAddress);
            return this;
        }
        @CustomType.Setter
        public Builder netId(String netId) {
            this.netId = Objects.requireNonNull(netId);
            return this;
        }
        @CustomType.Setter
        public Builder nicId(String nicId) {
            this.nicId = Objects.requireNonNull(nicId);
            return this;
        }
        @CustomType.Setter
        public Builder privateDnsName(String privateDnsName) {
            this.privateDnsName = Objects.requireNonNull(privateDnsName);
            return this;
        }
        @CustomType.Setter
        public Builder privateIps(List<GetNicsNicPrivateIp> privateIps) {
            this.privateIps = Objects.requireNonNull(privateIps);
            return this;
        }
        public Builder privateIps(GetNicsNicPrivateIp... privateIps) {
            return privateIps(List.of(privateIps));
        }
        @CustomType.Setter
        public Builder securityGroups(List<GetNicsNicSecurityGroup> securityGroups) {
            this.securityGroups = Objects.requireNonNull(securityGroups);
            return this;
        }
        public Builder securityGroups(GetNicsNicSecurityGroup... securityGroups) {
            return securityGroups(List.of(securityGroups));
        }
        @CustomType.Setter
        public Builder state(String state) {
            this.state = Objects.requireNonNull(state);
            return this;
        }
        @CustomType.Setter
        public Builder subnetId(String subnetId) {
            this.subnetId = Objects.requireNonNull(subnetId);
            return this;
        }
        @CustomType.Setter
        public Builder subregionName(String subregionName) {
            this.subregionName = Objects.requireNonNull(subregionName);
            return this;
        }
        @CustomType.Setter
        public Builder tags(List<GetNicsNicTag> tags) {
            this.tags = Objects.requireNonNull(tags);
            return this;
        }
        public Builder tags(GetNicsNicTag... tags) {
            return tags(List.of(tags));
        }
        public GetNicsNic build() {
            final var o = new GetNicsNic();
            o.accountId = accountId;
            o.description = description;
            o.isSourceDestChecked = isSourceDestChecked;
            o.linkNics = linkNics;
            o.linkPublicIps = linkPublicIps;
            o.macAddress = macAddress;
            o.netId = netId;
            o.nicId = nicId;
            o.privateDnsName = privateDnsName;
            o.privateIps = privateIps;
            o.securityGroups = securityGroups;
            o.state = state;
            o.subnetId = subnetId;
            o.subregionName = subregionName;
            o.tags = tags;
            return o;
        }
    }
}
