// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.outscale.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.outscale.outputs.GetNetAccessPointServicesFilter;
import com.pulumi.outscale.outputs.GetNetAccessPointServicesService;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class GetNetAccessPointServicesResult {
    private @Nullable List<GetNetAccessPointServicesFilter> filters;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private String requestId;
    /**
     * @return The names of the services you can use for Net access points.
     * 
     */
    private List<GetNetAccessPointServicesService> services;

    private GetNetAccessPointServicesResult() {}
    public List<GetNetAccessPointServicesFilter> filters() {
        return this.filters == null ? List.of() : this.filters;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String requestId() {
        return this.requestId;
    }
    /**
     * @return The names of the services you can use for Net access points.
     * 
     */
    public List<GetNetAccessPointServicesService> services() {
        return this.services;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNetAccessPointServicesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<GetNetAccessPointServicesFilter> filters;
        private String id;
        private String requestId;
        private List<GetNetAccessPointServicesService> services;
        public Builder() {}
        public Builder(GetNetAccessPointServicesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.filters = defaults.filters;
    	      this.id = defaults.id;
    	      this.requestId = defaults.requestId;
    	      this.services = defaults.services;
        }

        @CustomType.Setter
        public Builder filters(@Nullable List<GetNetAccessPointServicesFilter> filters) {
            this.filters = filters;
            return this;
        }
        public Builder filters(GetNetAccessPointServicesFilter... filters) {
            return filters(List.of(filters));
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder requestId(String requestId) {
            this.requestId = Objects.requireNonNull(requestId);
            return this;
        }
        @CustomType.Setter
        public Builder services(List<GetNetAccessPointServicesService> services) {
            this.services = Objects.requireNonNull(services);
            return this;
        }
        public Builder services(GetNetAccessPointServicesService... services) {
            return services(List.of(services));
        }
        public GetNetAccessPointServicesResult build() {
            final var o = new GetNetAccessPointServicesResult();
            o.filters = filters;
            o.id = id;
            o.requestId = requestId;
            o.services = services;
            return o;
        }
    }
}
