// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.outscale.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.outscale.outputs.GetSubregionsFilter;
import com.pulumi.outscale.outputs.GetSubregionsSubregion;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class GetSubregionsResult {
    private @Nullable List<GetSubregionsFilter> filters;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private String requestId;
    /**
     * @return Information about one or more Subregions.
     * 
     */
    private List<GetSubregionsSubregion> subregions;

    private GetSubregionsResult() {}
    public List<GetSubregionsFilter> filters() {
        return this.filters == null ? List.of() : this.filters;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String requestId() {
        return this.requestId;
    }
    /**
     * @return Information about one or more Subregions.
     * 
     */
    public List<GetSubregionsSubregion> subregions() {
        return this.subregions;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSubregionsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<GetSubregionsFilter> filters;
        private String id;
        private String requestId;
        private List<GetSubregionsSubregion> subregions;
        public Builder() {}
        public Builder(GetSubregionsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.filters = defaults.filters;
    	      this.id = defaults.id;
    	      this.requestId = defaults.requestId;
    	      this.subregions = defaults.subregions;
        }

        @CustomType.Setter
        public Builder filters(@Nullable List<GetSubregionsFilter> filters) {
            this.filters = filters;
            return this;
        }
        public Builder filters(GetSubregionsFilter... filters) {
            return filters(List.of(filters));
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder requestId(String requestId) {
            this.requestId = Objects.requireNonNull(requestId);
            return this;
        }
        @CustomType.Setter
        public Builder subregions(List<GetSubregionsSubregion> subregions) {
            this.subregions = Objects.requireNonNull(subregions);
            return this;
        }
        public Builder subregions(GetSubregionsSubregion... subregions) {
            return subregions(List.of(subregions));
        }
        public GetSubregionsResult build() {
            final var o = new GetSubregionsResult();
            o.filters = filters;
            o.id = id;
            o.requestId = requestId;
            o.subregions = subregions;
            return o;
        }
    }
}
