# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetVirtualGatewayResult',
    'AwaitableGetVirtualGatewayResult',
    'get_virtual_gateway',
    'get_virtual_gateway_output',
]

@pulumi.output_type
class GetVirtualGatewayResult:
    """
    A collection of values returned by getVirtualGateway.
    """
    def __init__(__self__, connection_type=None, filters=None, id=None, net_to_virtual_gateway_links=None, request_id=None, state=None, tags=None, virtual_gateway_id=None):
        if connection_type and not isinstance(connection_type, str):
            raise TypeError("Expected argument 'connection_type' to be a str")
        pulumi.set(__self__, "connection_type", connection_type)
        if filters and not isinstance(filters, list):
            raise TypeError("Expected argument 'filters' to be a list")
        pulumi.set(__self__, "filters", filters)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if net_to_virtual_gateway_links and not isinstance(net_to_virtual_gateway_links, list):
            raise TypeError("Expected argument 'net_to_virtual_gateway_links' to be a list")
        pulumi.set(__self__, "net_to_virtual_gateway_links", net_to_virtual_gateway_links)
        if request_id and not isinstance(request_id, str):
            raise TypeError("Expected argument 'request_id' to be a str")
        pulumi.set(__self__, "request_id", request_id)
        if state and not isinstance(state, str):
            raise TypeError("Expected argument 'state' to be a str")
        pulumi.set(__self__, "state", state)
        if tags and not isinstance(tags, list):
            raise TypeError("Expected argument 'tags' to be a list")
        pulumi.set(__self__, "tags", tags)
        if virtual_gateway_id and not isinstance(virtual_gateway_id, str):
            raise TypeError("Expected argument 'virtual_gateway_id' to be a str")
        pulumi.set(__self__, "virtual_gateway_id", virtual_gateway_id)

    @property
    @pulumi.getter(name="connectionType")
    def connection_type(self) -> str:
        """
        The type of VPN connection supported by the virtual gateway (only `ipsec.1` is supported).
        """
        return pulumi.get(self, "connection_type")

    @property
    @pulumi.getter
    def filters(self) -> Optional[Sequence['outputs.GetVirtualGatewayFilterResult']]:
        return pulumi.get(self, "filters")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="netToVirtualGatewayLinks")
    def net_to_virtual_gateway_links(self) -> Sequence['outputs.GetVirtualGatewayNetToVirtualGatewayLinkResult']:
        """
        The Net to which the virtual gateway is attached.
        """
        return pulumi.get(self, "net_to_virtual_gateway_links")

    @property
    @pulumi.getter(name="requestId")
    def request_id(self) -> str:
        return pulumi.get(self, "request_id")

    @property
    @pulumi.getter
    def state(self) -> str:
        """
        The state of the virtual gateway (`pending` \\| `available` \\| `deleting` \\| `deleted`).
        """
        return pulumi.get(self, "state")

    @property
    @pulumi.getter
    def tags(self) -> Sequence['outputs.GetVirtualGatewayTagResult']:
        """
        One or more tags associated with the virtual gateway.
        """
        return pulumi.get(self, "tags")

    @property
    @pulumi.getter(name="virtualGatewayId")
    def virtual_gateway_id(self) -> str:
        """
        The ID of the virtual gateway.
        """
        return pulumi.get(self, "virtual_gateway_id")


class AwaitableGetVirtualGatewayResult(GetVirtualGatewayResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetVirtualGatewayResult(
            connection_type=self.connection_type,
            filters=self.filters,
            id=self.id,
            net_to_virtual_gateway_links=self.net_to_virtual_gateway_links,
            request_id=self.request_id,
            state=self.state,
            tags=self.tags,
            virtual_gateway_id=self.virtual_gateway_id)


def get_virtual_gateway(connection_type: Optional[str] = None,
                        filters: Optional[Sequence[pulumi.InputType['GetVirtualGatewayFilterArgs']]] = None,
                        state: Optional[str] = None,
                        virtual_gateway_id: Optional[str] = None,
                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetVirtualGatewayResult:
    """
    Provides information about a virtual gateway.

    For more information on this resource, see the [User Guide](https://docs.outscale.com/en/userguide/About-Virtual-Private-Gateways.html).\\
    For more information on this resource actions, see the [API documentation](https://docs.outscale.com/api#3ds-outscale-api-virtualgateway).

    ## Example Usage

    ```python
    import pulumi
    import pulumi_outscale as outscale

    virtual_gateway01 = outscale.get_virtual_gateway(filters=[outscale.GetVirtualGatewayFilterArgs(
        name="virtual_gateway_ids",
        values=["vgw-12345678"],
    )])
    ```


    :param str connection_type: The type of VPN connection supported by the virtual gateway (only `ipsec.1` is supported).
    :param Sequence[pulumi.InputType['GetVirtualGatewayFilterArgs']] filters: A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
    :param str state: The state of the virtual gateway (`pending` \\| `available` \\| `deleting` \\| `deleted`).
    :param str virtual_gateway_id: The ID of the virtual gateway.
    """
    __args__ = dict()
    __args__['connectionType'] = connection_type
    __args__['filters'] = filters
    __args__['state'] = state
    __args__['virtualGatewayId'] = virtual_gateway_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('outscale:index/getVirtualGateway:getVirtualGateway', __args__, opts=opts, typ=GetVirtualGatewayResult).value

    return AwaitableGetVirtualGatewayResult(
        connection_type=pulumi.get(__ret__, 'connection_type'),
        filters=pulumi.get(__ret__, 'filters'),
        id=pulumi.get(__ret__, 'id'),
        net_to_virtual_gateway_links=pulumi.get(__ret__, 'net_to_virtual_gateway_links'),
        request_id=pulumi.get(__ret__, 'request_id'),
        state=pulumi.get(__ret__, 'state'),
        tags=pulumi.get(__ret__, 'tags'),
        virtual_gateway_id=pulumi.get(__ret__, 'virtual_gateway_id'))


@_utilities.lift_output_func(get_virtual_gateway)
def get_virtual_gateway_output(connection_type: Optional[pulumi.Input[Optional[str]]] = None,
                               filters: Optional[pulumi.Input[Optional[Sequence[pulumi.InputType['GetVirtualGatewayFilterArgs']]]]] = None,
                               state: Optional[pulumi.Input[Optional[str]]] = None,
                               virtual_gateway_id: Optional[pulumi.Input[Optional[str]]] = None,
                               opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetVirtualGatewayResult]:
    """
    Provides information about a virtual gateway.

    For more information on this resource, see the [User Guide](https://docs.outscale.com/en/userguide/About-Virtual-Private-Gateways.html).\\
    For more information on this resource actions, see the [API documentation](https://docs.outscale.com/api#3ds-outscale-api-virtualgateway).

    ## Example Usage

    ```python
    import pulumi
    import pulumi_outscale as outscale

    virtual_gateway01 = outscale.get_virtual_gateway(filters=[outscale.GetVirtualGatewayFilterArgs(
        name="virtual_gateway_ids",
        values=["vgw-12345678"],
    )])
    ```


    :param str connection_type: The type of VPN connection supported by the virtual gateway (only `ipsec.1` is supported).
    :param Sequence[pulumi.InputType['GetVirtualGatewayFilterArgs']] filters: A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
    :param str state: The state of the virtual gateway (`pending` \\| `available` \\| `deleting` \\| `deleted`).
    :param str virtual_gateway_id: The ID of the virtual gateway.
    """
    ...
