# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetImageResult',
    'AwaitableGetImageResult',
    'get_image',
    'get_image_output',
]

@pulumi.output_type
class GetImageResult:
    """
    A collection of values returned by getImage.
    """
    def __init__(__self__, account_alias=None, account_id=None, architecture=None, block_device_mappings=None, boot_modes=None, creation_date=None, description=None, file_location=None, filters=None, id=None, image_id=None, image_name=None, image_type=None, is_public=None, permissions=None, permissions_to_launches=None, product_codes=None, request_id=None, root_device_name=None, root_device_type=None, secure_boot=None, state=None, state_comments=None, tags=None):
        if account_alias and not isinstance(account_alias, str):
            raise TypeError("Expected argument 'account_alias' to be a str")
        pulumi.set(__self__, "account_alias", account_alias)
        if account_id and not isinstance(account_id, str):
            raise TypeError("Expected argument 'account_id' to be a str")
        pulumi.set(__self__, "account_id", account_id)
        if architecture and not isinstance(architecture, str):
            raise TypeError("Expected argument 'architecture' to be a str")
        pulumi.set(__self__, "architecture", architecture)
        if block_device_mappings and not isinstance(block_device_mappings, list):
            raise TypeError("Expected argument 'block_device_mappings' to be a list")
        pulumi.set(__self__, "block_device_mappings", block_device_mappings)
        if boot_modes and not isinstance(boot_modes, list):
            raise TypeError("Expected argument 'boot_modes' to be a list")
        pulumi.set(__self__, "boot_modes", boot_modes)
        if creation_date and not isinstance(creation_date, str):
            raise TypeError("Expected argument 'creation_date' to be a str")
        pulumi.set(__self__, "creation_date", creation_date)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if file_location and not isinstance(file_location, str):
            raise TypeError("Expected argument 'file_location' to be a str")
        pulumi.set(__self__, "file_location", file_location)
        if filters and not isinstance(filters, list):
            raise TypeError("Expected argument 'filters' to be a list")
        pulumi.set(__self__, "filters", filters)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if image_id and not isinstance(image_id, str):
            raise TypeError("Expected argument 'image_id' to be a str")
        pulumi.set(__self__, "image_id", image_id)
        if image_name and not isinstance(image_name, str):
            raise TypeError("Expected argument 'image_name' to be a str")
        pulumi.set(__self__, "image_name", image_name)
        if image_type and not isinstance(image_type, str):
            raise TypeError("Expected argument 'image_type' to be a str")
        pulumi.set(__self__, "image_type", image_type)
        if is_public and not isinstance(is_public, bool):
            raise TypeError("Expected argument 'is_public' to be a bool")
        pulumi.set(__self__, "is_public", is_public)
        if permissions and not isinstance(permissions, list):
            raise TypeError("Expected argument 'permissions' to be a list")
        pulumi.set(__self__, "permissions", permissions)
        if permissions_to_launches and not isinstance(permissions_to_launches, list):
            raise TypeError("Expected argument 'permissions_to_launches' to be a list")
        pulumi.set(__self__, "permissions_to_launches", permissions_to_launches)
        if product_codes and not isinstance(product_codes, list):
            raise TypeError("Expected argument 'product_codes' to be a list")
        pulumi.set(__self__, "product_codes", product_codes)
        if request_id and not isinstance(request_id, str):
            raise TypeError("Expected argument 'request_id' to be a str")
        pulumi.set(__self__, "request_id", request_id)
        if root_device_name and not isinstance(root_device_name, str):
            raise TypeError("Expected argument 'root_device_name' to be a str")
        pulumi.set(__self__, "root_device_name", root_device_name)
        if root_device_type and not isinstance(root_device_type, str):
            raise TypeError("Expected argument 'root_device_type' to be a str")
        pulumi.set(__self__, "root_device_type", root_device_type)
        if secure_boot and not isinstance(secure_boot, bool):
            raise TypeError("Expected argument 'secure_boot' to be a bool")
        pulumi.set(__self__, "secure_boot", secure_boot)
        if state and not isinstance(state, str):
            raise TypeError("Expected argument 'state' to be a str")
        pulumi.set(__self__, "state", state)
        if state_comments and not isinstance(state_comments, list):
            raise TypeError("Expected argument 'state_comments' to be a list")
        pulumi.set(__self__, "state_comments", state_comments)
        if tags and not isinstance(tags, list):
            raise TypeError("Expected argument 'tags' to be a list")
        pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter(name="accountAlias")
    def account_alias(self) -> _builtins.str:
        """
        The account alias of the owner of the OMI.
        """
        return pulumi.get(self, "account_alias")

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> _builtins.str:
        """
        The account ID of the owner of the OMI.
        """
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter
    def architecture(self) -> _builtins.str:
        """
        The architecture of the OMI.
        """
        return pulumi.get(self, "architecture")

    @_builtins.property
    @pulumi.getter(name="blockDeviceMappings")
    def block_device_mappings(self) -> Sequence['outputs.GetImageBlockDeviceMappingResult']:
        """
        One or more block device mappings.
        """
        return pulumi.get(self, "block_device_mappings")

    @_builtins.property
    @pulumi.getter(name="bootModes")
    def boot_modes(self) -> Sequence[_builtins.str]:
        """
        The boot modes compatible with the OMI. Possible values: `uefi` | `legacy`.
        """
        return pulumi.get(self, "boot_modes")

    @_builtins.property
    @pulumi.getter(name="creationDate")
    def creation_date(self) -> _builtins.str:
        """
        The date and time (UTC) at which the OMI was created.
        """
        return pulumi.get(self, "creation_date")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        The description of the OMI.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="fileLocation")
    def file_location(self) -> _builtins.str:
        """
        The location from which the OMI files were created.
        """
        return pulumi.get(self, "file_location")

    @_builtins.property
    @pulumi.getter
    def filters(self) -> Optional[Sequence['outputs.GetImageFilterResult']]:
        return pulumi.get(self, "filters")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="imageId")
    def image_id(self) -> Optional[_builtins.str]:
        """
        The ID of the OMI.
        """
        return pulumi.get(self, "image_id")

    @_builtins.property
    @pulumi.getter(name="imageName")
    def image_name(self) -> _builtins.str:
        """
        The name of the OMI.
        """
        return pulumi.get(self, "image_name")

    @_builtins.property
    @pulumi.getter(name="imageType")
    def image_type(self) -> _builtins.str:
        """
        The type of the OMI.
        """
        return pulumi.get(self, "image_type")

    @_builtins.property
    @pulumi.getter(name="isPublic")
    def is_public(self) -> _builtins.bool:
        return pulumi.get(self, "is_public")

    @_builtins.property
    @pulumi.getter
    def permissions(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "permissions")

    @_builtins.property
    @pulumi.getter(name="permissionsToLaunches")
    def permissions_to_launches(self) -> Sequence['outputs.GetImagePermissionsToLaunchResult']:
        """
        Permissions for the resource.
        """
        return pulumi.get(self, "permissions_to_launches")

    @_builtins.property
    @pulumi.getter(name="productCodes")
    def product_codes(self) -> Sequence[_builtins.str]:
        """
        The product codes associated with the OMI.
        """
        return pulumi.get(self, "product_codes")

    @_builtins.property
    @pulumi.getter(name="requestId")
    def request_id(self) -> _builtins.str:
        return pulumi.get(self, "request_id")

    @_builtins.property
    @pulumi.getter(name="rootDeviceName")
    def root_device_name(self) -> _builtins.str:
        """
        The name of the root device.
        """
        return pulumi.get(self, "root_device_name")

    @_builtins.property
    @pulumi.getter(name="rootDeviceType")
    def root_device_type(self) -> _builtins.str:
        """
        The type of root device used by the OMI (always `bsu`).
        """
        return pulumi.get(self, "root_device_type")

    @_builtins.property
    @pulumi.getter(name="secureBoot")
    def secure_boot(self) -> _builtins.bool:
        """
        Whether secure boot is activated or not.
        """
        return pulumi.get(self, "secure_boot")

    @_builtins.property
    @pulumi.getter
    def state(self) -> _builtins.str:
        """
        The state of the OMI (`pending` \\| `available` \\| `failed`).
        """
        return pulumi.get(self, "state")

    @_builtins.property
    @pulumi.getter(name="stateComments")
    def state_comments(self) -> Sequence['outputs.GetImageStateCommentResult']:
        """
        Information about the change of state.
        """
        return pulumi.get(self, "state_comments")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Sequence['outputs.GetImageTagResult']:
        """
        One or more tags associated with the OMI.
        """
        return pulumi.get(self, "tags")


class AwaitableGetImageResult(GetImageResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetImageResult(
            account_alias=self.account_alias,
            account_id=self.account_id,
            architecture=self.architecture,
            block_device_mappings=self.block_device_mappings,
            boot_modes=self.boot_modes,
            creation_date=self.creation_date,
            description=self.description,
            file_location=self.file_location,
            filters=self.filters,
            id=self.id,
            image_id=self.image_id,
            image_name=self.image_name,
            image_type=self.image_type,
            is_public=self.is_public,
            permissions=self.permissions,
            permissions_to_launches=self.permissions_to_launches,
            product_codes=self.product_codes,
            request_id=self.request_id,
            root_device_name=self.root_device_name,
            root_device_type=self.root_device_type,
            secure_boot=self.secure_boot,
            state=self.state,
            state_comments=self.state_comments,
            tags=self.tags)


def get_image(block_device_mappings: Optional[Sequence[Union['GetImageBlockDeviceMappingArgs', 'GetImageBlockDeviceMappingArgsDict']]] = None,
              filters: Optional[Sequence[Union['GetImageFilterArgs', 'GetImageFilterArgsDict']]] = None,
              image_id: Optional[_builtins.str] = None,
              permissions: Optional[Sequence[_builtins.str]] = None,
              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetImageResult:
    """
    Provides information about an image.

    For more information on this resource, see the [User Guide](https://docs.outscale.com/en/userguide/About-OMIs.html).\\
    For more information on this resource actions, see the [API documentation](https://docs.outscale.com/api#3ds-outscale-api-image).

    ## Example Usage

    ```python
    import pulumi
    import pulumi_outscale as outscale

    image01 = outscale.get_image(filters=[{
        "name": "image_ids",
        "values": ["ami-12345678"],
    }])
    ```


    :param Sequence[Union['GetImageBlockDeviceMappingArgs', 'GetImageBlockDeviceMappingArgsDict']] block_device_mappings: One or more block device mappings.
    :param Sequence[Union['GetImageFilterArgs', 'GetImageFilterArgsDict']] filters: A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
    :param _builtins.str image_id: The ID of the OMI.
    """
    __args__ = dict()
    __args__['blockDeviceMappings'] = block_device_mappings
    __args__['filters'] = filters
    __args__['imageId'] = image_id
    __args__['permissions'] = permissions
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('outscale:index/getImage:getImage', __args__, opts=opts, typ=GetImageResult).value

    return AwaitableGetImageResult(
        account_alias=pulumi.get(__ret__, 'account_alias'),
        account_id=pulumi.get(__ret__, 'account_id'),
        architecture=pulumi.get(__ret__, 'architecture'),
        block_device_mappings=pulumi.get(__ret__, 'block_device_mappings'),
        boot_modes=pulumi.get(__ret__, 'boot_modes'),
        creation_date=pulumi.get(__ret__, 'creation_date'),
        description=pulumi.get(__ret__, 'description'),
        file_location=pulumi.get(__ret__, 'file_location'),
        filters=pulumi.get(__ret__, 'filters'),
        id=pulumi.get(__ret__, 'id'),
        image_id=pulumi.get(__ret__, 'image_id'),
        image_name=pulumi.get(__ret__, 'image_name'),
        image_type=pulumi.get(__ret__, 'image_type'),
        is_public=pulumi.get(__ret__, 'is_public'),
        permissions=pulumi.get(__ret__, 'permissions'),
        permissions_to_launches=pulumi.get(__ret__, 'permissions_to_launches'),
        product_codes=pulumi.get(__ret__, 'product_codes'),
        request_id=pulumi.get(__ret__, 'request_id'),
        root_device_name=pulumi.get(__ret__, 'root_device_name'),
        root_device_type=pulumi.get(__ret__, 'root_device_type'),
        secure_boot=pulumi.get(__ret__, 'secure_boot'),
        state=pulumi.get(__ret__, 'state'),
        state_comments=pulumi.get(__ret__, 'state_comments'),
        tags=pulumi.get(__ret__, 'tags'))
def get_image_output(block_device_mappings: Optional[pulumi.Input[Optional[Sequence[Union['GetImageBlockDeviceMappingArgs', 'GetImageBlockDeviceMappingArgsDict']]]]] = None,
                     filters: Optional[pulumi.Input[Optional[Sequence[Union['GetImageFilterArgs', 'GetImageFilterArgsDict']]]]] = None,
                     image_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                     permissions: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetImageResult]:
    """
    Provides information about an image.

    For more information on this resource, see the [User Guide](https://docs.outscale.com/en/userguide/About-OMIs.html).\\
    For more information on this resource actions, see the [API documentation](https://docs.outscale.com/api#3ds-outscale-api-image).

    ## Example Usage

    ```python
    import pulumi
    import pulumi_outscale as outscale

    image01 = outscale.get_image(filters=[{
        "name": "image_ids",
        "values": ["ami-12345678"],
    }])
    ```


    :param Sequence[Union['GetImageBlockDeviceMappingArgs', 'GetImageBlockDeviceMappingArgsDict']] block_device_mappings: One or more block device mappings.
    :param Sequence[Union['GetImageFilterArgs', 'GetImageFilterArgsDict']] filters: A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
    :param _builtins.str image_id: The ID of the OMI.
    """
    __args__ = dict()
    __args__['blockDeviceMappings'] = block_device_mappings
    __args__['filters'] = filters
    __args__['imageId'] = image_id
    __args__['permissions'] = permissions
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('outscale:index/getImage:getImage', __args__, opts=opts, typ=GetImageResult)
    return __ret__.apply(lambda __response__: GetImageResult(
        account_alias=pulumi.get(__response__, 'account_alias'),
        account_id=pulumi.get(__response__, 'account_id'),
        architecture=pulumi.get(__response__, 'architecture'),
        block_device_mappings=pulumi.get(__response__, 'block_device_mappings'),
        boot_modes=pulumi.get(__response__, 'boot_modes'),
        creation_date=pulumi.get(__response__, 'creation_date'),
        description=pulumi.get(__response__, 'description'),
        file_location=pulumi.get(__response__, 'file_location'),
        filters=pulumi.get(__response__, 'filters'),
        id=pulumi.get(__response__, 'id'),
        image_id=pulumi.get(__response__, 'image_id'),
        image_name=pulumi.get(__response__, 'image_name'),
        image_type=pulumi.get(__response__, 'image_type'),
        is_public=pulumi.get(__response__, 'is_public'),
        permissions=pulumi.get(__response__, 'permissions'),
        permissions_to_launches=pulumi.get(__response__, 'permissions_to_launches'),
        product_codes=pulumi.get(__response__, 'product_codes'),
        request_id=pulumi.get(__response__, 'request_id'),
        root_device_name=pulumi.get(__response__, 'root_device_name'),
        root_device_type=pulumi.get(__response__, 'root_device_type'),
        secure_boot=pulumi.get(__response__, 'secure_boot'),
        state=pulumi.get(__response__, 'state'),
        state_comments=pulumi.get(__response__, 'state_comments'),
        tags=pulumi.get(__response__, 'tags')))
