// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Outscale.Inputs
{

    public sealed class LoadBalancerPolicySourceSecurityGroupGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The account ID of the owner of the security group.
        /// </summary>
        [Input("securityGroupAccountId")]
        public Input<string>? SecurityGroupAccountId { get; set; }

        /// <summary>
        /// The name of the security group.
        /// </summary>
        [Input("securityGroupName")]
        public Input<string>? SecurityGroupName { get; set; }

        public LoadBalancerPolicySourceSecurityGroupGetArgs()
        {
        }
        public static new LoadBalancerPolicySourceSecurityGroupGetArgs Empty => new LoadBalancerPolicySourceSecurityGroupGetArgs();
    }
}
