// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Outscale.Inputs
{

    public sealed class NicLinkNicGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If true, the NIC is deleted when the VM is terminated.
        /// </summary>
        [Input("deleteOnVmDeletion")]
        public Input<string>? DeleteOnVmDeletion { get; set; }

        /// <summary>
        /// The device index for the NIC attachment (between `1` and `7`, both included).
        /// </summary>
        [Input("deviceNumber")]
        public Input<int>? DeviceNumber { get; set; }

        /// <summary>
        /// The ID of the NIC to attach.
        /// </summary>
        [Input("linkNicId")]
        public Input<string>? LinkNicId { get; set; }

        /// <summary>
        /// The state of the NIC (`available` \| `attaching` \| `in-use` \| `detaching`).
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        /// <summary>
        /// The account ID of the owner of the VM.
        /// </summary>
        [Input("vmAccountId")]
        public Input<string>? VmAccountId { get; set; }

        /// <summary>
        /// The ID of the VM.
        /// </summary>
        [Input("vmId")]
        public Input<string>? VmId { get; set; }

        public NicLinkNicGetArgs()
        {
        }
        public static new NicLinkNicGetArgs Empty => new NicLinkNicGetArgs();
    }
}
