// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Outscale.Inputs
{

    public sealed class VmBlockDeviceMappingArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Information about the BSU volume to create.
        /// </summary>
        [Input("bsu")]
        public Input<Inputs.VmBlockDeviceMappingBsuArgs>? Bsu { get; set; }

        /// <summary>
        /// The device name for the volume. For a root device, you must use `/dev/sda1`. For other volumes, you must use `/dev/sdX`, `/dev/sdXX`, `/dev/xvdX`, or `/dev/xvdXX` (where the first `X` is a letter between `b` and `z`, and the second `X` is a letter between `a` and `z`).
        /// </summary>
        [Input("deviceName")]
        public Input<string>? DeviceName { get; set; }

        /// <summary>
        /// Removes the device which is included in the block device mapping of the OMI.
        /// </summary>
        [Input("noDevice")]
        public Input<string>? NoDevice { get; set; }

        /// <summary>
        /// The name of the virtual device (`ephemeralN`).
        /// </summary>
        [Input("virtualDeviceName")]
        public Input<string>? VirtualDeviceName { get; set; }

        public VmBlockDeviceMappingArgs()
        {
        }
        public static new VmBlockDeviceMappingArgs Empty => new VmBlockDeviceMappingArgs();
    }
}
