name: 📦 Prerequisites

on:
    workflow_call:
        inputs:
            is_pr:
                type: boolean
                required: true
            is_automated:
                type: boolean
                required: true
            default_branch:
                type: string
                required: true
        outputs:
            version:
                description: "Provider version being built"
                value: ${{ jobs.prerequisites.outputs.version }}

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
    PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
    TF_APPEND_USER_AGENT: pulumi

jobs:
    prerequisites:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.provider-version.outputs.version }}
        steps:
            - name: 📦 Checkout repo
              uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - name: 🔧 Set provider version
              uses: pulumi/provider-version-action@v1
              id: provider-version
              with:
                  major-version: 1
                  set-env: "PROVIDER_VERSION"
            - name: 📦 Cache examples generation
              uses: actions/cache@v4
              with:
                  path: |
                      .pulumi/examples-cache
                  key: ${{ runner.os }}-${{ hashFiles('provider/go.sum') }}
            - name: 🔧 Setup tools
              uses: ./.github/actions/setup-tools
              with:
                  tools: go, pulumictl, pulumicli, schema-tools
            - name: 🔧 Prepare local workspace
              run: make prepare_local_workspace
            - name: 🔨 Generate schema
              run: make schema
            - name: 🔨 Build provider binary
              run: make provider
            - if: inputs.is_pr
              name: ✅ Check schema is valid
              run: |
                  EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
                  {
                    echo "SCHEMA_CHANGES<<$EOF";
                    schema-tools compare -r github://api.github.com/outscale -p outscale -o "${{ inputs.default_branch }}" -n --local-path=provider/cmd/pulumi-resource-outscale/schema.json;
                    echo "$EOF";
                  } >> "$GITHUB_ENV"
            - if: inputs.is_pr && inputs.is_automated == false && github.actor != 'dependabot[bot]'
              name: 💬 Comment on PR with schema check details
              uses: thollander/actions-comment-pull-request@v3
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  comment-tag: schemaCheck
                  message: >+
                      ${{ env.SCHEMA_CHANGES }}


                      Maintainer note: consult the [runbook](https://github.com/pulumi/platform-providers-team/blob/main/playbooks/tf-provider-updating.md) for dealing with any breaking changes.

            - name: 📦 Upload artifacts
              uses: ./.github/actions/upload-prerequisites
