name: 🔖 Release
on:
    push:
        tags:
            - v*.*.*
            - "!v*.*.*-**"

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
    PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
    TF_APPEND_USER_AGENT: pulumi
jobs:
    prerequisites:
        name: 📦 Prerequisites
        uses: ./.github/workflows/prerequisites.yml
        secrets: inherit
        with:
            default_branch: ${{ github.event.repository.default_branch }}
            is_pr: ${{ github.event_name == 'pull_request' }}
            is_automated: ${{ github.actor == 'dependabot[bot]' }}

    build_provider:
        name: 📦 Build provider
        uses: ./.github/workflows/build_provider.yml
        needs: prerequisites
        secrets: inherit
        with:
            version: ${{ needs.prerequisites.outputs.version }}

    build_sdk:
        name: 📦 Build SDK
        needs: prerequisites
        uses: ./.github/workflows/build_sdk.yml
        secrets: inherit
        with:
            version: ${{ needs.prerequisites.outputs.version }}

    license_check:
        name: 📄 License Check
        uses: ./.github/workflows/license.yml
        secrets: inherit

    publish:
        name: 🚀 Publish
        permissions:
            contents: write
            pull-requests: write
        needs:
            - prerequisites
            - build_provider
            - test
            - license_check
        uses: ./.github/workflows/publish.yml
        secrets: inherit
        with:
            version: ${{ needs.prerequisites.outputs.version }}
            isPrerelease: false

    test:
        name: 🧪 Test
        uses: ./.github/workflows/test.yml
        needs:
            - prerequisites
            - build_provider
            - build_sdk
        permissions:
            contents: read
        secrets: inherit
        with:
            version: ${{ needs.prerequisites.outputs.version }}
