name: release
on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write
  id-token: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.goversion}}
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: pulumi/pulumictl
      - name: build
        run: |
          make build_python
          make build_nodejs
          cp -v ./sdk/python/bin/dist/pulumi_outscale-*.tar.gz sdk/python.tar.gz
          cd sdk/nodejs/bin/ && npm pack && cd ../../../
          cp -v sdk/nodejs/bin/pulumi-outscale-*tgz sdk/nodejs.tar.gz
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Upload python artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-sdk.tar.gz
          path: |
            ./sdk/python.tar.gz
      - name: Upload nodejs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-sdk.tar.gz
          path: |
            ./sdk/nodejs.tar.gz
      - name: publish sdks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PROVIDER: outscale
          PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          PYPI_USERNAME: "__token__"
        uses: pulumi/pulumi-package-publisher@main
        with:
          sdk: nodejs
          version: "v0.0.2"
