// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides information about Certificate Authorities (CAs).
 *
 * For more information on this resource, see the [User Guide](https://docs.outscale.com/en/userguide/About-API-Access-Rules.html).\
 * For more information on this resource actions, see the [API documentation](https://docs.outscale.com/api#3ds-outscale-api-ca).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as outscale from "@outscale/pulumi-outscale";
 *
 * const cas01 = outscale.getCas({
 *     filters: [{
 *         name: "ca_ids",
 *         values: [
 *             "ca-12345678",
 *             "ca-87654321",
 *         ],
 *     }],
 * });
 * ```
 */
export function getCas(args?: GetCasArgs, opts?: pulumi.InvokeOptions): Promise<GetCasResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("outscale:index/getCas:getCas", {
        "filters": args.filters,
    }, opts);
}

/**
 * A collection of arguments for invoking getCas.
 */
export interface GetCasArgs {
    /**
     * A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
     */
    filters?: inputs.GetCasFilter[];
}

/**
 * A collection of values returned by getCas.
 */
export interface GetCasResult {
    /**
     * Information about one or more CAs.
     */
    readonly cas: outputs.GetCasCa[];
    readonly filters?: outputs.GetCasFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly requestId: string;
}
/**
 * Provides information about Certificate Authorities (CAs).
 *
 * For more information on this resource, see the [User Guide](https://docs.outscale.com/en/userguide/About-API-Access-Rules.html).\
 * For more information on this resource actions, see the [API documentation](https://docs.outscale.com/api#3ds-outscale-api-ca).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as outscale from "@outscale/pulumi-outscale";
 *
 * const cas01 = outscale.getCas({
 *     filters: [{
 *         name: "ca_ids",
 *         values: [
 *             "ca-12345678",
 *             "ca-87654321",
 *         ],
 *     }],
 * });
 * ```
 */
export function getCasOutput(args?: GetCasOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCasResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("outscale:index/getCas:getCas", {
        "filters": args.filters,
    }, opts);
}

/**
 * A collection of arguments for invoking getCas.
 */
export interface GetCasOutputArgs {
    /**
     * A combination of a filter name and one or more filter values. You can specify this argument for as many filter names as you need. The filter name can be any of the following:
     */
    filters?: pulumi.Input<pulumi.Input<inputs.GetCasFilterArgs>[]>;
}
