// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getPublicCatalog(opts?: pulumi.InvokeOptions): Promise<GetPublicCatalogResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("outscale:index/getPublicCatalog:getPublicCatalog", {
    }, opts);
}

/**
 * A collection of values returned by getPublicCatalog.
 */
export interface GetPublicCatalogResult {
    readonly catalogs: outputs.GetPublicCatalogCatalog[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly requestId: string;
}
export function getPublicCatalogOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPublicCatalogResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("outscale:index/getPublicCatalog:getPublicCatalog", {
    }, opts);
}
