// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides information about users.
 *
 * For more information on this resource, see the [User Guide](https://docs.outscale.com/en/userguide/About-EIM-Users.html).\
 * For more information on this resource actions, see the [API documentation](https://docs.outscale.com/api.html#createuser).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as outscale from "@outscale/pulumi-outscale";
 *
 * const users_2 = outscale.getUsers({
 *     filters: [{
 *         name: "user_ids",
 *         values: [
 *             "XXXXXXXXXXXXXXXX",
 *             "YYYYYYYYYY",
 *         ],
 *     }],
 * });
 * ```
 */
export function getUsers(args?: GetUsersArgs, opts?: pulumi.InvokeOptions): Promise<GetUsersResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("outscale:index/getUsers:getUsers", {
        "filters": args.filters,
    }, opts);
}

/**
 * A collection of arguments for invoking getUsers.
 */
export interface GetUsersArgs {
    filters?: inputs.GetUsersFilter[];
}

/**
 * A collection of values returned by getUsers.
 */
export interface GetUsersResult {
    readonly filters?: outputs.GetUsersFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * A list of EIM users.
     */
    readonly users: outputs.GetUsersUser[];
}
/**
 * Provides information about users.
 *
 * For more information on this resource, see the [User Guide](https://docs.outscale.com/en/userguide/About-EIM-Users.html).\
 * For more information on this resource actions, see the [API documentation](https://docs.outscale.com/api.html#createuser).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as outscale from "@outscale/pulumi-outscale";
 *
 * const users_2 = outscale.getUsers({
 *     filters: [{
 *         name: "user_ids",
 *         values: [
 *             "XXXXXXXXXXXXXXXX",
 *             "YYYYYYYYYY",
 *         ],
 *     }],
 * });
 * ```
 */
export function getUsersOutput(args?: GetUsersOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetUsersResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("outscale:index/getUsers:getUsers", {
        "filters": args.filters,
    }, opts);
}

/**
 * A collection of arguments for invoking getUsers.
 */
export interface GetUsersOutputArgs {
    filters?: pulumi.Input<pulumi.Input<inputs.GetUsersFilterArgs>[]>;
}
