// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getVmTypes(args?: GetVmTypesArgs, opts?: pulumi.InvokeOptions): Promise<GetVmTypesResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("outscale:index/getVmTypes:getVmTypes", {
        "filters": args.filters,
    }, opts);
}

/**
 * A collection of arguments for invoking getVmTypes.
 */
export interface GetVmTypesArgs {
    filters?: inputs.GetVmTypesFilter[];
}

/**
 * A collection of values returned by getVmTypes.
 */
export interface GetVmTypesResult {
    readonly filters?: outputs.GetVmTypesFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly requestId: string;
    readonly vmTypes: outputs.GetVmTypesVmType[];
}
export function getVmTypesOutput(args?: GetVmTypesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetVmTypesResult> {
    return pulumi.output(args).apply((a: any) => getVmTypes(a, opts))
}

/**
 * A collection of arguments for invoking getVmTypes.
 */
export interface GetVmTypesOutputArgs {
    filters?: pulumi.Input<pulumi.Input<inputs.GetVmTypesFilterArgs>[]>;
}
