// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages a user group.
 *
 * For more information on this resource, see the [User Guide](https://docs.outscale.com/en/userguide/About-EIM-Groups.html).\
 * For more information on this resource actions, see the [API documentation](https://docs.outscale.com/api.html#createusergroup).
 *
 * ## Example Usage
 *
 * ### Create a user group
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as outscale from "@outscale/pulumi-outscale";
 *
 * const group_1 = new outscale.UserGroup("group-1", {
 *     userGroupName: "Group-TF-test-1",
 *     path: "/terraform/",
 * });
 * ```
 *
 * ### Link a policy to a user group
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as outscale from "@outscale/pulumi-outscale";
 *
 * const group_1 = new outscale.UserGroup("group-1", {
 *     userGroupName: "Group-TF-test-1",
 *     policies: [{
 *         policyOrn: policy_2.orn,
 *         defaultVersionId: "V2",
 *     }],
 * });
 * ```
 *
 * ### Add a user to a user group
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as outscale from "@outscale/pulumi-outscale";
 *
 * const group_1 = new outscale.UserGroup("group-1", {
 *     userGroupName: "Group-TF-test-1",
 *     users: [
 *         {
 *             userName: "user-name-1",
 *             path: "/terraform/",
 *         },
 *         {
 *             userName: "user-name-2",
 *         },
 *     ],
 * });
 * ```
 *
 * ### Create a user group, and add a user and a policy to it
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as outscale from "@outscale/pulumi-outscale";
 *
 * const group_1 = new outscale.UserGroup("group-1", {
 *     userGroupName: "Group-TF-test-1",
 *     users: [
 *         {
 *             userName: "user-name-1",
 *             path: "/terraform/",
 *         },
 *         {
 *             userName: "user-name-2",
 *         },
 *     ],
 *     policies: [{
 *         policyOrn: policy_2.orn,
 *         versionId: "V2",
 *     }],
 * });
 * ```
 *
 * ## Import
 *
 * A user group can be imported using its group ID. For example:
 *
 * ```sh
 * $ pulumi import outscale:index/userGroup:UserGroup group1 user_group_id
 * ```
 */
export class UserGroup extends pulumi.CustomResource {
    /**
     * Get an existing UserGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserGroupState, opts?: pulumi.CustomResourceOptions): UserGroup {
        return new UserGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'outscale:index/userGroup:UserGroup';

    /**
     * Returns true if the given object is an instance of UserGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is UserGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === UserGroup.__pulumiType;
    }

    /**
     * The date and time (UTC) of creation of the user group.
     */
    declare public /*out*/ readonly creationDate: pulumi.Output<string>;
    /**
     * The date and time (UTC) of the last modification of the user group.
     */
    declare public /*out*/ readonly lastModificationDate: pulumi.Output<string>;
    /**
     * The Outscale Resource Name (ORN) of the user group. For more information, see [Resource Identifiers](https://docs.outscale.com/en/userguide/Resource-Identifiers.html).
     */
    declare public /*out*/ readonly orn: pulumi.Output<string>;
    /**
     * The path to the group. If not specified, it is set to a slash (`/`).
     */
    declare public readonly path: pulumi.Output<string>;
    declare public readonly policies: pulumi.Output<outputs.UserGroupPolicy[] | undefined>;
    declare public readonly timeouts: pulumi.Output<outputs.UserGroupTimeouts | undefined>;
    /**
     * The ID of the user group.
     */
    declare public /*out*/ readonly userGroupId: pulumi.Output<string>;
    /**
     * The name of the group.
     */
    declare public readonly userGroupName: pulumi.Output<string>;
    declare public readonly users: pulumi.Output<outputs.UserGroupUser[] | undefined>;

    /**
     * Create a UserGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserGroupArgs | UserGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserGroupState | undefined;
            resourceInputs["creationDate"] = state?.creationDate;
            resourceInputs["lastModificationDate"] = state?.lastModificationDate;
            resourceInputs["orn"] = state?.orn;
            resourceInputs["path"] = state?.path;
            resourceInputs["policies"] = state?.policies;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["userGroupId"] = state?.userGroupId;
            resourceInputs["userGroupName"] = state?.userGroupName;
            resourceInputs["users"] = state?.users;
        } else {
            const args = argsOrState as UserGroupArgs | undefined;
            if (args?.userGroupName === undefined && !opts.urn) {
                throw new Error("Missing required property 'userGroupName'");
            }
            resourceInputs["path"] = args?.path;
            resourceInputs["policies"] = args?.policies;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["userGroupName"] = args?.userGroupName;
            resourceInputs["users"] = args?.users;
            resourceInputs["creationDate"] = undefined /*out*/;
            resourceInputs["lastModificationDate"] = undefined /*out*/;
            resourceInputs["orn"] = undefined /*out*/;
            resourceInputs["userGroupId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(UserGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering UserGroup resources.
 */
export interface UserGroupState {
    /**
     * The date and time (UTC) of creation of the user group.
     */
    creationDate?: pulumi.Input<string>;
    /**
     * The date and time (UTC) of the last modification of the user group.
     */
    lastModificationDate?: pulumi.Input<string>;
    /**
     * The Outscale Resource Name (ORN) of the user group. For more information, see [Resource Identifiers](https://docs.outscale.com/en/userguide/Resource-Identifiers.html).
     */
    orn?: pulumi.Input<string>;
    /**
     * The path to the group. If not specified, it is set to a slash (`/`).
     */
    path?: pulumi.Input<string>;
    policies?: pulumi.Input<pulumi.Input<inputs.UserGroupPolicy>[]>;
    timeouts?: pulumi.Input<inputs.UserGroupTimeouts>;
    /**
     * The ID of the user group.
     */
    userGroupId?: pulumi.Input<string>;
    /**
     * The name of the group.
     */
    userGroupName?: pulumi.Input<string>;
    users?: pulumi.Input<pulumi.Input<inputs.UserGroupUser>[]>;
}

/**
 * The set of arguments for constructing a UserGroup resource.
 */
export interface UserGroupArgs {
    /**
     * The path to the group. If not specified, it is set to a slash (`/`).
     */
    path?: pulumi.Input<string>;
    policies?: pulumi.Input<pulumi.Input<inputs.UserGroupPolicy>[]>;
    timeouts?: pulumi.Input<inputs.UserGroupTimeouts>;
    /**
     * The name of the group.
     */
    userGroupName: pulumi.Input<string>;
    users?: pulumi.Input<pulumi.Input<inputs.UserGroupUser>[]>;
}
